### ISSUE TITLE
Ignores my config/tinymce.yml config options

### ISSUE THREAD

**Issue by taniarv** [spree-contrib/spree_editor#93]
I am trying to modify the displayed toolbar within the tinymce_editor. 
This is how my config/tinymce.yml looks like: 
 ```
# TinyMCE Options
language: 
  - es
plugins:
  - link anchor code table paste
# Each line is a toolbar
toolbar: 
  - styleselect | formatselect | fontsizeselect | bold italic strikethrough | alignleft aligncenter alignright alignjustify | link code | table
 ```

But it continues on showing the default options: 

![captura de pantalla 2015-01-29 a la s 18 03 19](https://cloud.githubusercontent.com/assets/939360/5962039/1f929030-a7e1-11e4-81c5-a649bce0b316.png)

I am using branch 2-4-stable, rails 4.2 and ruby 2.1.4. 
I have been doing some research in order to try to fix it myself, but no luck. Any help or guidance is appreciated.

**Comment by rbngzlv** [comment]
Hola @taniarv 

What you need to change? I think that tinymce is loading your config file and not ignoring this, because:
- You changed the language in config file, and the editor has changed the language
- All elements declared in your toolbar configuration appears in the editor toolbar, in the same order and groups

What happens if you remove an item from the toolbar configuration, for example the bold element, it remains visible in the toolbar? If it remains, try to clear cache and restart the server.

If you want to hide the top menu bar, add this in the default section:
```
menubar: false
```
This is how my config/tinymce.yml looks like: 
```
# TinyMCE Options
default:
  mode: "exact"
  theme: "modern"
  skin: "light"
  language: "<%= I18n.locale.to_s.split('-')[0].downcase %>"
  schema: "html5-strict"
  element_format: "html"
  resize: true
  menubar: false
  preview_styles: 'font-family font-size font-weight font-style text-decoration text-transform'

  plugins:
    - charmap
    - lists
    - paste
    - textcolor
    - link
    - fullscreen

  # Each line is a toolbar
  toolbar:
    - bold italic underline | bullist numlist blockquote | alignleft aligncenter alignright | link unlink | fullscreen # Toolbar 1
```
And editor looks:
![tinymce_editor](https://cloud.githubusercontent.com/assets/2051199/6093353/3b1d9026-af01-11e4-9e3c-fdbb2c32f37e.png)
